import { jsPDF } from 'jspdf';
import { formatCurrency } from './currencies';

export interface BalanceDetail {
  fromUser: string;
  toUser: string;
  amount: number;
}

export interface BalanceSummary {
  title: string;
  date: string;
  currency: string;
  totalOwed: number;
  totalOwing: number;
  netBalance: number;
  details: BalanceDetail[];
}

export function generateBalancePDF(summary: BalanceSummary): void {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  let y = 20;

  // Header
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('Balance Summary', pageWidth / 2, y, { align: 'center' });
  y += 15;

  // Subtitle
  doc.setFontSize(14);
  doc.setFont('helvetica', 'normal');
  doc.text(summary.title, pageWidth / 2, y, { align: 'center' });
  y += 8;

  // Date
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(`Generated on ${summary.date}`, pageWidth / 2, y, { align: 'center' });
  doc.setTextColor(0);
  y += 20;

  // Summary box
  doc.setFillColor(248, 250, 252);
  doc.roundedRect(margin, y, pageWidth - 2 * margin, 45, 3, 3, 'F');
  y += 12;

  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');

  // Total Owed (green)
  doc.setTextColor(34, 197, 94);
  doc.text('Total Owed to You:', margin + 10, y);
  doc.text(formatCurrency(summary.totalOwed, summary.currency), pageWidth - margin - 10, y, { align: 'right' });
  y += 12;

  // Total Owing (red)
  doc.setTextColor(239, 68, 68);
  doc.text('Total You Owe:', margin + 10, y);
  doc.text(formatCurrency(summary.totalOwing, summary.currency), pageWidth - margin - 10, y, { align: 'right' });
  y += 12;

  // Net Balance
  const netColor = summary.netBalance >= 0 ? [34, 197, 94] : [239, 68, 68];
  doc.setTextColor(netColor[0], netColor[1], netColor[2]);
  doc.text('Net Balance:', margin + 10, y);
  const netPrefix = summary.netBalance >= 0 ? '+' : '';
  doc.text(netPrefix + formatCurrency(summary.netBalance, summary.currency), pageWidth - margin - 10, y, { align: 'right' });
  doc.setTextColor(0);
  y += 25;

  // Details section
  if (summary.details.length > 0) {
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Settlement Details', margin, y);
    y += 12;

    // Table header
    doc.setFillColor(241, 245, 249);
    doc.rect(margin, y - 5, pageWidth - 2 * margin, 10, 'F');
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text('From', margin + 5, y);
    doc.text('To', margin + 65, y);
    doc.text('Amount', pageWidth - margin - 5, y, { align: 'right' });
    y += 12;

    // Table rows
    doc.setFont('helvetica', 'normal');
    for (const detail of summary.details) {
      if (y > 270) {
        doc.addPage();
        y = 20;
      }

      // Alternate row colors
      if (summary.details.indexOf(detail) % 2 === 0) {
        doc.setFillColor(250, 250, 250);
        doc.rect(margin, y - 5, pageWidth - 2 * margin, 10, 'F');
      }

      doc.text(detail.fromUser, margin + 5, y);
      doc.text(detail.toUser, margin + 65, y);
      doc.setTextColor(239, 68, 68);
      doc.text(formatCurrency(detail.amount, summary.currency), pageWidth - margin - 5, y, { align: 'right' });
      doc.setTextColor(0);
      y += 10;
    }
  } else {
    doc.setFontSize(12);
    doc.setTextColor(100);
    doc.text('No outstanding balances to settle.', pageWidth / 2, y, { align: 'center' });
    doc.setTextColor(0);
  }

  // Footer
  y = doc.internal.pageSize.getHeight() - 15;
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text('Generated by Expensable', pageWidth / 2, y, { align: 'center' });

  // Open PDF in new tab
  const pdfBlob = doc.output('blob');
  const url = URL.createObjectURL(pdfBlob);
  window.open(url, '_blank');
}

export function isMobileDevice(): boolean {
  if (typeof window === 'undefined') return false;

  return /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent) ||
    (window.innerWidth <= 768);
}
